### ISSUE TITLE
[Scopes] can't select an icon to display in scope selector

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#572] opened 2015-10-19 10:07 UTC
default scope selector uses the scope to "define the css class for the scope".

![image](https://cloud.githubusercontent.com/assets/14293391/10574961/995eb26c-7659-11e5-831a-88156be3e651.png)

![image](https://cloud.githubusercontent.com/assets/14293391/10574969/a7dbfeda-7659-11e5-84b8-a98afbd6dc0b.png)

But the move to material has changed the way icons are rendered:
![image](https://cloud.githubusercontent.com/assets/14293391/10574986/c1cd2274-7659-11e5-8b6d-7c9eb1623505.png)

So you end up with the code of your scope written in a undefined font.
![image](https://cloud.githubusercontent.com/assets/14293391/10575018/f2cc5994-7659-11e5-9d24-382f875ef897.png)

**Comment by pierbrisson** [comment] 2015-10-20 09:13
linked to https://github.com/KleeGroup/focus-components/issues/552 i believe

**Comment by sgoretti** [comment] 2015-10-20 09:22
Could be, though,I'd go a little farther : instead of creating your own font, why isn't there a system where you could feed the path to an icon? Or define a css class with a background image pointing to that icon.

Either way, the fact the the code of the scope defines the icon seems wrong to me. The code of the scope defines the scope : in Linkit, its values are project or job, and I don't want to have to create a font where these words match some icons, I'd rather leave these codes as is and have another value in the scope config for the icon?.

I mean, technically, the getActiveScopeIcon does nothing: you feed it a code, it searches the code in the scope config and returns... the code.

**Comment by pierr** [comment] 2015-10-23 12:17
Duplicate of https://github.com/KleeGroup/focus-components/issues/552

**Comment by pierr** [comment] 2015-10-23 13:57
https://github.com/KleeGroup/focus-components/blob/develop/src/search/search-bar/scope.js#L114

**Comment by pierr** [comment] 2015-10-23 13:58
We need to be able top provide other props to the icon.

**Comment by pierr** [comment] 2015-10-23 14:01
```jsx
_renderScopeList() {
        const {scopesId} = this;
        const {list: scopeList, value} = this.props;
        return (
            <ul className={`mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect`} data-focus='search-bar-scopes' htmlFor={scopesId} ref='scopeDropdown'>
                {0 < scopeList.length && scopeList.map(scope => {
                   const {code, label, ...otherScopeProps} = scope;
                    const scopeId = uniqueId('scopes_');
                    const isActive = value === code;
                    return (
                        <li className='mdl-menu__item' data-active={isActive} key={scope.code || scopeId} onClick={this._getScopeClickHandler(scope)}>
                            {scope.code &&
                                <Icon name={code}  ...otherScopeProps/>
                            }
                            <span>{label}</span>
                        </li>
                    );
                })}
                {0 === scopeList.length &&
                    <li className='mdl-menu__item'>
                        {this.i18n('scopes.empty')}
                    </li>
                }
            </ul>
        );
    }
```

**Comment by sgoretti** [comment] 2015-12-01 17:34
Fixed in the scope list, not in the selected scope

**Closed** 2015-12-14 10:05 UTC
Labels: Backlog, Bug, Critical
