### ISSUE TITLE
[Form] Global attribute 'isEdit' is not always coherent with the content of the spa.

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#988] opened 2016-02-23 10:02 UTC
### Context

Within the application i wished to display some component and change the css according the the global attribute 'isEdit'. 
### Current behaviour

This attribute is set to true on the 'edit' button and set to false on the 'cancel' and 'save' buttons.
But if we open a page with a form already in edit mode, the variable is not set to true.
Moreover, if we left the page in edition with any link, the variable is not set to false.
### Expected behaviour

On each load of the page, something must parse all form in the spa, and set 'isEdit' to true if there is at least one form in edition mode, else set it to false. It solves all problems.
### Versions

```
"focus-components": "^0.8.6",
"focus-core": "^0.12.4",
"focus-file": "^0.1.2",
```
### Tips

``` javascript
_onLoad{
    isEdit = false;
    for(Form f : spa.getForm()){
        isEdit = isEdit || f.getIsEdit();
    }
    dataFocus.setDataMode(isEdit ? 'edit' : 'consult');
}
```

**Comment by pierr** [comment] 2016-03-18 13:38
@Pandakls I don't understant you tips ? 
According to me on the `componentWillMount` this should be processed.

**Comment by JohnnP** [comment] 2017-07-07 13:13
@Pandakls I close it; If the issue is still occuring, reopen it.

**Closed by JohnnP** 2017-07-07 13:13 UTC
Labels: Enhancement, Form, Minor, v2.x.x
