### ISSUE TITLE
[Date component] : The calendar doesn't show and it's impossible to set a date

### ISSUE THREAD

**Issue by julienKlee** [KleeGroup/focus-components#154] opened 2015-07-31 14:03 UTC
I'm using firefox (v39) and for every date, I don't see the calendar. 
Plus, when I try to update the date in the field, it set the date with random values. 
The component isn't usuable in firefox.

For example, when I try to change the date I can have something like that : 
![sans titre](https://cloud.githubusercontent.com/assets/13589034/9008896/9e32dc96-379d-11e5-809d-91fa7da1973c.png)

**Comment by pierr** [comment] 2015-07-31 14:04
Duplicate of https://github.com/KleeGroup/focus-components/issues/146

**Closed** 2015-08-04 11:41 UTC
Labels: bug, duplicate
