### ISSUE TITLE
[AdvancedSearch][Facets] conditional facets

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#961] opened 2016-02-04 16:18 UTC
### Current behaviour

Facets with lots of values can be found even if they're facets covering sub-divisions of another facet.
It's easier to understand with an example: the world is divided in 5 geographical areas containing each several sub-divisions called (in this example) geomarkets, each of these containing several countries.
![image](https://cloud.githubusercontent.com/assets/14293391/12821192/9678f680-cb62-11e5-8cd3-5233fdfee2d9.png)

We currently see all three facets, though country will contain lots of values since there a many more countries than there are areas.
### Expected behaviour

Having facets appear only if the parent facet has a selected value.
![image](https://cloud.githubusercontent.com/assets/14293391/12821294/0984f0f2-cb63-11e5-80d6-11995f03528a.png)

Then, when selecting a value (such as Asia), the Geomarket facet will appear:
![image](https://cloud.githubusercontent.com/assets/14293391/12821314/1b4350ae-cb63-11e5-81ec-8d9dc8e374dc.png)

And when selecting a Geomarket, the country facet will appear.
![image](https://cloud.githubusercontent.com/assets/14293391/12821330/39dc98a4-cb63-11e5-96be-be73e0831643.png)
### Versions

Focus-core: 0.12.3
Focus-components: 0.8.5

**Comment by TomGallon** [comment] 2016-09-05 20:05
depending on server side ?
@NPi2Loup

**Comment by GuenoleK** [comment] 2016-10-17 12:20
@NPi2Loup what do you think about the suggestion here ?

**Comment by JohnnP** [comment] 2017-07-07 13:15
@sgoretti I close it. If the issue is still occuring, reopen it.

**Closed** 2017-07-07 13:16 UTC
Labels: Enhancement, External, Search, Wontfix
