### ISSUE TITLE
[Scroll] Impossible to scroll to the bottom for specific body height

### ISSUE THREAD

**Issue by durandx** [KleeGroup/focus-components#1040] opened 2016-03-09 09:04 UTC
# Current behaviour

For certain page (with a specific height) it is not possible to scroll down to the bottom due to a bad computation of the cartridge/summary component.

I've investigated and it seems the following event takes places in this order for the scroll component :
1- render (in cartridge mode)
2- scrollPosition called (here the state is switch to summary mode)
3- render (in summary mode) here the render is correct
4- notifySizeChange
5- scrollPosition (the state is switch to cartridge mode)
6- render (in cartridge mode)
7- notifySizeChange

Moreover, If I refresh the problematic page with 'F5' the problem disappear (I can scroll down in summary mode).
# Expected behaviour

Fix the wrong computation of the cartridge mode (in state : canDeploy, isDeploy)
## Versions

Focus-core: Prebuild 0.13.0
Focus-components: 0.8.6

**Comment by durandx** [comment] 2016-03-10 09:03
FYI, our body height is 955 (document.body.getBoundingClientRect())

**Comment by pierr** [comment] 2016-03-18 13:22
@durandx This needs time to analyse and reproduce.

**Comment by pierr** [comment] 2016-03-18 13:23
How many pages are concerned ?
What do you mean by specific height?

**Comment by durandx** [comment] 2016-03-21 14:31
@pierr I've sent you an url in which you can reproduce the bug at will. You will see that **depending on the number of time the render method is called** i can scroll to the bottom or not : 
- 3 render calls when I navigate and I **cannot** scroll down
- 2 render calls when I refresh the page but I **can** scroll down)

**Comment by durandx** [comment] 2016-03-21 14:34
Page concerned: All page can be concerned by this bug. It depend of the data displayed in the page. It happens very frequently in some page and rather infrequently on anothers...

**Comment by pierr** [comment] 2016-03-31 09:50
As seen together, the problems seems to be in the calculation and depends from the scrollbar height.

**Comment by pierr** [comment] 2016-03-31 09:50
Depending on the navigation context.

**Comment by pierr** [comment] 2016-03-31 11:47
@durandx  Can you check the `FocusCore.applicationStore.getValue().canDeploy` value in the case where it is not working ?

**Comment by durandx** [comment] 2016-03-31 12:54
FocusCore.applicationStore est undefined

**Comment by durandx** [comment] 2016-03-31 12:55
FocusCore.application.builtInStore.getValue().canDeploy
true

**Comment by pierr** [comment] 2016-04-01 08:00
Thanks

**Comment by JohnnP** [comment] 2017-07-07 13:07
@durandx I close it. If this issue is still occuring, reopen it.

**Closed by JohnnP** 2017-07-07 13:07 UTC
Labels: Bug, Critical, v2.x.x
