### ISSUE TITLE
[FocusFiles] Loading a file deleting all data on view + Error send by server not handled

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#690] opened 2015-11-19 10:17 UTC
### Context
I'v got a form with both a dropfile section and classic fieldFor. 
Architecture : DetailPage > Block > PageList > Line > action that open a popup containing the form.

Here the content of my popup :
![image](https://cloud.githubusercontent.com/assets/7700690/11267933/8bec2548-8eae-11e5-85b4-602877d038fa.png)

### Actual behaviour
issue 1 : if i load a file in the drop zone, all my fields gone blank (no matter where the data comes from).
issue 2 : If i save my object and get an error from server (on fields for instance). Then i can correct the fields, the filedropper still detect the file that i loaded but during the second save : file not found and i'm rejected from server (i must reload a file > lose my data, retype them etc...)

### Expected behaviour
1) Keep data fields when i load a file
2) Keep the saved file even when there's errors happening during the save.

### Versions
Focus-core : 0.11.3
Focus-component: 0.7.4
Focus-File: 0.1.2

**Comment by pierr** [comment] 2015-11-20 07:17
@Pandakls The repository for this extension is https://github.com/KleeGroup/focus-file , can you recreate your issue here ?

**Comment by pierr** [comment] 2015-11-20 07:19
I think there is a misunderstanding of the component behaviour here.
The UploadFileComponent should be separated from the form other elements. We will come see you in order to detail the way to do it.

**Comment by Pandakls** [comment] 2015-11-25 09:44
Yes but i want my save action to save both the file and the data under

**Comment by Bernardstanislas** [comment] 2015-11-26 09:38
@Pandakls as seen with you, this is due to a `setState` in your component. The first and best solution is to separated the component holding Focus File from the form, and link them with a common parent.
The second solution is to keep the previous state when you upload a file, and restore it afterwards, as you did.

In any case, that's the expected behaviour, closing this now.

**Closed by Bernardstanislas** 2015-11-26 09:38 UTC
Labels: Backlog, Question
