### ISSUE TITLE
[FofusFile] - Mutiple error message when an upload fails

### ISSUE THREAD

**Issue by Pandakls** [KleeGroup/focus-components#652] opened 2015-11-05 10:31 UTC
### Context
Hi,
I've a classic file uploader :

```javascript
                <div className='upload'>
                    <FocusFile paramName='file'
                               ref='focusFile'
                               url={action}/>
                    {this.displayFor('fileName')}
                </div>
```

With the classical handler function :
```javascript
    componentDidUpdate() {
        this.setEventOnFocusFile();
    },
    componentDidMount() {
        this.setEventOnFocusFile();
    },
    componentWillUnmount() {
        this.refs.focusFile.props.store.removeFilesChangeListener(this._onFileStoreChange);
    },
    setEventOnFocusFile() {
        if(this.refs.focusFile) {
            this.refs.focusFile.props.store.addFilesChangeListener(this._onFileStoreChange);
            this.refs.focusFile.dropzone.on('success', this._setFileKey);
        }
    },
```
Where i have added the message error :
```javascript
    _onFileStoreChange() {
        const files = this.refs.focusFile.props.store.getFiles();
        this.setState({files}, () => {
            if (this.state.files.pop().status === 'error'){
                Focus.message.addErrorMessage('common.fichierTropGros');
            }
        });
    },
```

### Actual behaviour
But this one triggers multiple times (3 in normal execution and more if we stop the ansynchrone request).
Stan added a consol.log on the event received in the function : 
_onFileStoreChange(event)

And the three events are totally, TOTALLY identical.
So there's no way to distinguish one of them and make a filter in order to send only one error message.
### Expected behaviour
Only one message send or Somthing to distinguish the events.

:hamster: 

### Versions
Focus-core : 0.11.0
Focus-component: 0.7.3-3
Focus-File: 0.1.2

**Comment by Bernardstanislas** [comment] 2015-11-06 18:30
Might be linked to the Focus File project, we'll investigate

**Comment by Bernardstanislas** [comment] 2015-11-06 18:31
I put no milestone yet since I don't know which project is responsible for this.

**Comment by Bernardstanislas** [comment] 2015-11-26 13:46
I don't think that the `FocusFile` is responsible for this, since I tested and it only triggers one call.
So I can't reproduce right now...

**Comment by Bernardstanislas** [comment] 2015-11-26 13:49
I just understood the issue here. You are registering a `addFilesChangeListener` in the `componentDidUpdate` method, that's why you have this problem. Closing now.

**Closed** 2015-11-26 13:50 UTC
Labels: Closed
